# Generated by Django 3.2.6 on 2021-08-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='order_date',
            new_name='ordered_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discounted_proce',
            new_name='discounted_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='selling_proce',
            new_name='selling_price',
        ),
    ]
